# Generated by Django 4.0.4 on 2022-06-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_like_liked_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
