# Generated by Django 4.0.4 on 2022-06-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
