# Generated by Django 4.0.4 on 2022-06-05 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_image_alter_listing_date_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 0, 38, 19, 304599)),
        ),
    ]
