# Generated by Django 3.2.5 on 2022-06-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20220605_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
    ]
